### ISSUE TITLE
Support head dimension 16？

### ISSUE THREAD

**Issue by alann-github** [lucidrains/flash-cosine-sim-attention#7]
Hello and thanks for your work.
Can flash-cosine-sim-attention support head dimension 16？32 is too big for my model, so I wonder do you have any plans to support head dimension 16 as flash-attention didi?

**Comment by lucidrains** [comment]
@alann-github Hi and thanks for your interest

I've checked in head size of 16 in 0.1.28, but only for f32

Turns out supporting different head dimensions is far from trivial when working in CUDA. There are various constraints to satisfy, and performance characteristics also differ (in other words, I cannot guarantee performance is that great just yet)

I'll get to f16 head size 16 some other day, once I have made some further strides in improving perf
